// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240406100212_Start")]
    partial class Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronic"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Book"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcangeCategory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExchangeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ExcangeCategory = "Book",
                            ExchangeStatus = true,
                            ImageUrl = "/images/1.jpg",
                            Price = 45500m,
                            ProductName = "Compter",
                            Rating = 5,
                            Summary = ""
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ExcangeCategory = "Keyboard",
                            ExchangeStatus = false,
                            ImageUrl = "/images/2.jpg",
                            Price = 25000m,
                            ProductName = "Tablet",
                            Rating = 3,
                            Summary = ""
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            ExcangeCategory = "Mouse",
                            ExchangeStatus = true,
                            ImageUrl = "/images/3.jpg",
                            Price = 35700m,
                            ProductName = "Mobile Phone",
                            Rating = 4,
                            Summary = ""
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ExcangeCategory = "Mobile Phone",
                            ExchangeStatus = false,
                            ImageUrl = "/images/4.jpg",
                            Price = 3500m,
                            ProductName = "Tablet",
                            Rating = 2,
                            Summary = ""
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            ExcangeCategory = "Dune",
                            ExchangeStatus = true,
                            ImageUrl = "/images/5.jpg",
                            Price = 5350m,
                            ProductName = "Hamlet",
                            Rating = 5,
                            Summary = ""
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            ExcangeCategory = "Manga",
                            ExchangeStatus = true,
                            ImageUrl = "/images/6.jpg",
                            Price = 575m,
                            ProductName = "Book",
                            Rating = 1,
                            Summary = ""
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
